services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    entrypoint: ["/bin/sh", "-c", "rm -rf /var/lib/postgresql/data/* && docker-entrypoint.sh postgres"]
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s