services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 10s
      retries: 10
      start_period: 60s
      timeout: 10s
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped  # Added
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=postgres1234'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  # Added
volumes:
  ollama_data:
  postgres_data: